// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/redis/go-redis/v9"
	"github.com/user_service/internal/event"
	"github.com/user_service/internal/event/worker"
	"github.com/user_service/internal/handler"
	"github.com/user_service/internal/initialize"
	"github.com/user_service/internal/middleware"
	"github.com/user_service/internal/repository"
	"github.com/user_service/internal/router"
	"github.com/user_service/internal/router/auth_router"
	"github.com/user_service/internal/router/health_check"
	"github.com/user_service/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitRouter(db *gorm.DB, rdb *redis.Client) (*router.Router, error) {
	authRepository := repository.NewAuthRepository(db)
	tokenBlacklist := service.NewRedisBlacklist(rdb)
	jwtService := initialize.InitJWT()
	v := provideEventQueue()
	dispatcher := event.NewDispatcher(v)
	authServiceInterface := service.NewAuthService(authRepository, tokenBlacklist, jwtService, dispatcher)
	authHandler := handler.NewAuthHandler(authServiceInterface)
	authMiddleware := middleware.NewAuthMiddleware(jwtService, tokenBlacklist)
	rateLimitMiddleware := middleware.NewRateLimitMiddleware(rdb)
	authRouter := auth_router.NewAuthRouter(authHandler, authMiddleware, rateLimitMiddleware)
	healthHandler := handler.NewHealthHandler()
	healthRouter := health_check.NewHealthRouter(healthHandler)
	int2 := provideWorkerCount()
	loginWorker := worker.NewLoginWorker(authRepository, dispatcher, int2)
	routerRouter := router.NewRouter(authRouter, healthRouter, dispatcher, loginWorker)
	return routerRouter, nil
}

// wire.go:

func provideEventQueue() chan event.Event {
	return make(chan event.Event, 1000)
}

func provideWorkerCount() int {
	return 5
}
