// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/auth_service/internal/handler"
	"github.com/auth_service/internal/initialize"
	"github.com/auth_service/internal/middleware"
	"github.com/auth_service/internal/repository"
	"github.com/auth_service/internal/router"
	"github.com/auth_service/internal/router/auth_router"
	"github.com/auth_service/internal/router/health_check"
	"github.com/auth_service/internal/service"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitRouter(db *gorm.DB, rdb *redis.Client) (*router.Router, error) {
	authRepository := repository.NewAuthRepository(db)
	tokenBlacklist := service.NewRedisBlacklist(rdb)
	jwtService := initialize.InitJWT()
	authServiceInterface := service.NewAuthService(authRepository, tokenBlacklist, jwtService)
	authHandler := handler.NewAuthHandler(authServiceInterface)
	authMiddleware := middleware.NewAuthMiddleware(jwtService, tokenBlacklist)
	authRouter := auth_router.NewAuthRouter(authHandler, authMiddleware)
	healthHandler := handler.NewHealthHandler()
	healthRouter := health_check.NewHealthRouter(healthHandler)
	routerRouter := router.NewRouter(authRouter, healthRouter)
	return routerRouter, nil
}
