services:
  mysql:
    image: mysql:8.0
    container_name: auth_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_password
    ports:
      - "33007:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7
    container_name: auth_redis
    restart: always
    ports:
      - "63709:63709"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
